--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Mar 27 2013 18:54
-- Script Generated by Database Design Studio 2.21.3 
--

--
-- Drop Table    : 'Fagforening'   
--
DROP TABLE Fagforening
GO
--
-- Drop Table    : 'Projektleder'   
--
DROP TABLE Projektleder
GO
--
-- Drop Table    : 'Firmabil'   
--
DROP TABLE Firmabil
GO
--
-- Drop Table    : 'Tekniker'   
--
DROP TABLE Tekniker
GO
--
-- Drop Table    : 'Sekretaer'   
--
DROP TABLE Sekretaer
GO
--
-- Drop Table    : 'Fastansaettelse'   
--
DROP TABLE Fastansaettelse
GO
--
-- Drop Table    : 'Timeloen'   
--
DROP TABLE Timeloen
GO
--
-- Drop Table    : 'Ansaettelsesforhold'   
--
DROP TABLE Ansaettelsesforhold
GO
--
-- Drop Table    : 'Civilingenioer'   
--
DROP TABLE Civilingenioer
GO
--
-- Drop Table    : 'Diplomingenioer'   
--
DROP TABLE Diplomingenioer
GO
--
-- Drop Table    : 'Ingenioer'   
--
DROP TABLE Ingenioer
GO
--
-- Drop Table    : 'Direktoer'   
--
DROP TABLE Direktoer
GO
--
-- Drop Table    : 'Ansat'   
--
DROP TABLE Ansat
GO
--
-- Drop Table    : 'Virksomhed'   
--
DROP TABLE Virksomhed
GO
